name: C CI

on:
  push:
    branches: [ master ]
    paths:
     - 'PythonTCP/*'

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: make check
      run: make check
